version: '3.4'

services:
  paymentservice:
    image: paymentservice:latest
    container_name: payment-service
    restart: always
    build:
      context: ./MockServer
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8082:3000
  consighmentservice:
    image: consighmentservice:latest
    container_name: consighment-service
    restart: always
    build:
      context: .
      dockerfile: ./ConsighmentService/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:80
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: abc
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
