version: '3.4'

services:
  paymentservice:
    image: paymentservice:latest
    container_name: payment-service
    restart: always
    build:
      context: ./MockServer
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8082:8082
  consighmentservice:
    image: consighmentservice:latest
    container_name: consighment-service
    restart: always
    build:
      context: .
      dockerfile: ./ConsighmentService/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5100
